extraction:
  cpp:
    prepare:
      packages:
        - libreadline-dev
        - flex
        - bison
        - perl
        - libipc-run-perl
        - llvm-dev
        - libperl-dev
        - libpython3-dev
        - tcl-dev
        - libldap2-dev
        - libicu-dev
        - libxml2-utils
        - xsltproc
        - krb5-admin-server
        - krb5-kdc
        - krb5-user
        - slapd
        - ldap-utils
        - libssl-dev
        - pkg-config
        - locales-all
        - liblz4-dev
        - libzstd-dev
        - python3-distutils
    configure:
      command: ./configure --enable-cassert --enable-debug --enable-tap-tests --with-tcl --with-python --with-perl --with-ldap --with-ssl=openssl --with-icu --with-llvm --with-libxml --with-libxslt --with-lz4
