/*-------------------------------------------------------------------------
 *
 * readfuncs.switch.c
 *    Generated node infrastructure code
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/nodes/gen_node_support.pl
 *
 *-------------------------------------------------------------------------
 */
	if (MATCH("ALIAS", 5))
		return (Node *) _readAlias(ctx);
	if (MATCH("RANGEVAR", 8))
		return (Node *) _readRangeVar(ctx);
	if (MATCH("TABLEFUNC", 9))
		return (Node *) _readTableFunc(ctx);
	if (MATCH("INTOCLAUSE", 10))
		return (Node *) _readIntoClause(ctx);
	if (MATCH("VAR", 3))
		return (Node *) _readVar(ctx);
	if (MATCH("CONST", 5))
		return (Node *) _readConst(ctx);
	if (MATCH("PARAM", 5))
		return (Node *) _readParam(ctx);
	if (MATCH("AGGREF", 6))
		return (Node *) _readAggref(ctx);
	if (MATCH("GROUPINGFUNC", 12))
		return (Node *) _readGroupingFunc(ctx);
	if (MATCH("WINDOWFUNC", 10))
		return (Node *) _readWindowFunc(ctx);
	if (MATCH("WINDOWFUNCRUNCONDITION", 22))
		return (Node *) _readWindowFuncRunCondition(ctx);
	if (MATCH("MERGESUPPORTFUNC", 16))
		return (Node *) _readMergeSupportFunc(ctx);
	if (MATCH("SUBSCRIPTINGREF", 15))
		return (Node *) _readSubscriptingRef(ctx);
	if (MATCH("FUNCEXPR", 8))
		return (Node *) _readFuncExpr(ctx);
	if (MATCH("NAMEDARGEXPR", 12))
		return (Node *) _readNamedArgExpr(ctx);
	if (MATCH("OPEXPR", 6))
		return (Node *) _readOpExpr(ctx);
	if (MATCH("DISTINCTEXPR", 12))
		return (Node *) _readDistinctExpr(ctx);
	if (MATCH("NULLIFEXPR", 10))
		return (Node *) _readNullIfExpr(ctx);
	if (MATCH("SCALARARRAYOPEXPR", 17))
		return (Node *) _readScalarArrayOpExpr(ctx);
	if (MATCH("BOOLEXPR", 8))
		return (Node *) _readBoolExpr(ctx);
	if (MATCH("SUBLINK", 7))
		return (Node *) _readSubLink(ctx);
	if (MATCH("SUBPLAN", 7))
		return (Node *) _readSubPlan(ctx);
	if (MATCH("ALTERNATIVESUBPLAN", 18))
		return (Node *) _readAlternativeSubPlan(ctx);
	if (MATCH("FIELDSELECT", 11))
		return (Node *) _readFieldSelect(ctx);
	if (MATCH("FIELDSTORE", 10))
		return (Node *) _readFieldStore(ctx);
	if (MATCH("RELABELTYPE", 11))
		return (Node *) _readRelabelType(ctx);
	if (MATCH("COERCEVIAIO", 11))
		return (Node *) _readCoerceViaIO(ctx);
	if (MATCH("ARRAYCOERCEEXPR", 15))
		return (Node *) _readArrayCoerceExpr(ctx);
	if (MATCH("CONVERTROWTYPEEXPR", 18))
		return (Node *) _readConvertRowtypeExpr(ctx);
	if (MATCH("COLLATEEXPR", 11))
		return (Node *) _readCollateExpr(ctx);
	if (MATCH("CASEEXPR", 8))
		return (Node *) _readCaseExpr(ctx);
	if (MATCH("CASEWHEN", 8))
		return (Node *) _readCaseWhen(ctx);
	if (MATCH("CASETESTEXPR", 12))
		return (Node *) _readCaseTestExpr(ctx);
	if (MATCH("ARRAYEXPR", 9))
		return (Node *) _readArrayExpr(ctx);
	if (MATCH("ROWEXPR", 7))
		return (Node *) _readRowExpr(ctx);
	if (MATCH("ROWCOMPAREEXPR", 14))
		return (Node *) _readRowCompareExpr(ctx);
	if (MATCH("COALESCEEXPR", 12))
		return (Node *) _readCoalesceExpr(ctx);
	if (MATCH("MINMAXEXPR", 10))
		return (Node *) _readMinMaxExpr(ctx);
	if (MATCH("SQLVALUEFUNCTION", 16))
		return (Node *) _readSQLValueFunction(ctx);
	if (MATCH("XMLEXPR", 7))
		return (Node *) _readXmlExpr(ctx);
	if (MATCH("JSONFORMAT", 10))
		return (Node *) _readJsonFormat(ctx);
	if (MATCH("JSONRETURNING", 13))
		return (Node *) _readJsonReturning(ctx);
	if (MATCH("JSONVALUEEXPR", 13))
		return (Node *) _readJsonValueExpr(ctx);
	if (MATCH("JSONCONSTRUCTOREXPR", 19))
		return (Node *) _readJsonConstructorExpr(ctx);
	if (MATCH("JSONISPREDICATE", 15))
		return (Node *) _readJsonIsPredicate(ctx);
	if (MATCH("JSONBEHAVIOR", 12))
		return (Node *) _readJsonBehavior(ctx);
	if (MATCH("JSONEXPR", 8))
		return (Node *) _readJsonExpr(ctx);
	if (MATCH("JSONTABLEPATH", 13))
		return (Node *) _readJsonTablePath(ctx);
	if (MATCH("JSONTABLEPATHSCAN", 17))
		return (Node *) _readJsonTablePathScan(ctx);
	if (MATCH("JSONTABLESIBLINGJOIN", 20))
		return (Node *) _readJsonTableSiblingJoin(ctx);
	if (MATCH("NULLTEST", 8))
		return (Node *) _readNullTest(ctx);
	if (MATCH("BOOLEANTEST", 11))
		return (Node *) _readBooleanTest(ctx);
	if (MATCH("MERGEACTION", 11))
		return (Node *) _readMergeAction(ctx);
	if (MATCH("COERCETODOMAIN", 14))
		return (Node *) _readCoerceToDomain(ctx);
	if (MATCH("COERCETODOMAINVALUE", 19))
		return (Node *) _readCoerceToDomainValue(ctx);
	if (MATCH("SETTODEFAULT", 12))
		return (Node *) _readSetToDefault(ctx);
	if (MATCH("CURRENTOFEXPR", 13))
		return (Node *) _readCurrentOfExpr(ctx);
	if (MATCH("NEXTVALUEEXPR", 13))
		return (Node *) _readNextValueExpr(ctx);
	if (MATCH("INFERENCEELEM", 13))
		return (Node *) _readInferenceElem(ctx);
	if (MATCH("RETURNINGEXPR", 13))
		return (Node *) _readReturningExpr(ctx);
	if (MATCH("TARGETENTRY", 11))
		return (Node *) _readTargetEntry(ctx);
	if (MATCH("RANGETBLREF", 11))
		return (Node *) _readRangeTblRef(ctx);
	if (MATCH("JOINEXPR", 8))
		return (Node *) _readJoinExpr(ctx);
	if (MATCH("FROMEXPR", 8))
		return (Node *) _readFromExpr(ctx);
	if (MATCH("ONCONFLICTEXPR", 14))
		return (Node *) _readOnConflictExpr(ctx);
	if (MATCH("QUERY", 5))
		return (Node *) _readQuery(ctx);
	if (MATCH("TYPENAME", 8))
		return (Node *) _readTypeName(ctx);
	if (MATCH("COLUMNREF", 9))
		return (Node *) _readColumnRef(ctx);
	if (MATCH("PARAMREF", 8))
		return (Node *) _readParamRef(ctx);
	if (MATCH("A_EXPR", 6))
		return (Node *) _readA_Expr(ctx);
	if (MATCH("A_CONST", 7))
		return (Node *) _readA_Const(ctx);
	if (MATCH("TYPECAST", 8))
		return (Node *) _readTypeCast(ctx);
	if (MATCH("COLLATECLAUSE", 13))
		return (Node *) _readCollateClause(ctx);
	if (MATCH("ROLESPEC", 8))
		return (Node *) _readRoleSpec(ctx);
	if (MATCH("FUNCCALL", 8))
		return (Node *) _readFuncCall(ctx);
	if (MATCH("A_STAR", 6))
		return (Node *) _readA_Star(ctx);
	if (MATCH("A_INDICES", 9))
		return (Node *) _readA_Indices(ctx);
	if (MATCH("A_INDIRECTION", 13))
		return (Node *) _readA_Indirection(ctx);
	if (MATCH("A_ARRAYEXPR", 11))
		return (Node *) _readA_ArrayExpr(ctx);
	if (MATCH("RESTARGET", 9))
		return (Node *) _readResTarget(ctx);
	if (MATCH("MULTIASSIGNREF", 14))
		return (Node *) _readMultiAssignRef(ctx);
	if (MATCH("SORTBY", 6))
		return (Node *) _readSortBy(ctx);
	if (MATCH("WINDOWDEF", 9))
		return (Node *) _readWindowDef(ctx);
	if (MATCH("RANGESUBSELECT", 14))
		return (Node *) _readRangeSubselect(ctx);
	if (MATCH("RANGEFUNCTION", 13))
		return (Node *) _readRangeFunction(ctx);
	if (MATCH("RANGETABLEFUNC", 14))
		return (Node *) _readRangeTableFunc(ctx);
	if (MATCH("RANGETABLEFUNCCOL", 17))
		return (Node *) _readRangeTableFuncCol(ctx);
	if (MATCH("RANGETABLESAMPLE", 16))
		return (Node *) _readRangeTableSample(ctx);
	if (MATCH("COLUMNDEF", 9))
		return (Node *) _readColumnDef(ctx);
	if (MATCH("TABLELIKECLAUSE", 15))
		return (Node *) _readTableLikeClause(ctx);
	if (MATCH("INDEXELEM", 9))
		return (Node *) _readIndexElem(ctx);
	if (MATCH("DEFELEM", 7))
		return (Node *) _readDefElem(ctx);
	if (MATCH("LOCKINGCLAUSE", 13))
		return (Node *) _readLockingClause(ctx);
	if (MATCH("XMLSERIALIZE", 12))
		return (Node *) _readXmlSerialize(ctx);
	if (MATCH("PARTITIONELEM", 13))
		return (Node *) _readPartitionElem(ctx);
	if (MATCH("PARTITIONSPEC", 13))
		return (Node *) _readPartitionSpec(ctx);
	if (MATCH("PARTITIONBOUNDSPEC", 18))
		return (Node *) _readPartitionBoundSpec(ctx);
	if (MATCH("PARTITIONRANGEDATUM", 19))
		return (Node *) _readPartitionRangeDatum(ctx);
	if (MATCH("PARTITIONCMD", 12))
		return (Node *) _readPartitionCmd(ctx);
	if (MATCH("RANGETBLENTRY", 13))
		return (Node *) _readRangeTblEntry(ctx);
	if (MATCH("RTEPERMISSIONINFO", 17))
		return (Node *) _readRTEPermissionInfo(ctx);
	if (MATCH("RANGETBLFUNCTION", 16))
		return (Node *) _readRangeTblFunction(ctx);
	if (MATCH("TABLESAMPLECLAUSE", 17))
		return (Node *) _readTableSampleClause(ctx);
	if (MATCH("WITHCHECKOPTION", 15))
		return (Node *) _readWithCheckOption(ctx);
	if (MATCH("SORTGROUPCLAUSE", 15))
		return (Node *) _readSortGroupClause(ctx);
	if (MATCH("GROUPINGSET", 11))
		return (Node *) _readGroupingSet(ctx);
	if (MATCH("WINDOWCLAUSE", 12))
		return (Node *) _readWindowClause(ctx);
	if (MATCH("ROWMARKCLAUSE", 13))
		return (Node *) _readRowMarkClause(ctx);
	if (MATCH("WITHCLAUSE", 10))
		return (Node *) _readWithClause(ctx);
	if (MATCH("INFERCLAUSE", 11))
		return (Node *) _readInferClause(ctx);
	if (MATCH("ONCONFLICTCLAUSE", 16))
		return (Node *) _readOnConflictClause(ctx);
	if (MATCH("CTESEARCHCLAUSE", 15))
		return (Node *) _readCTESearchClause(ctx);
	if (MATCH("CTECYCLECLAUSE", 14))
		return (Node *) _readCTECycleClause(ctx);
	if (MATCH("COMMONTABLEEXPR", 15))
		return (Node *) _readCommonTableExpr(ctx);
	if (MATCH("MERGEWHENCLAUSE", 15))
		return (Node *) _readMergeWhenClause(ctx);
	if (MATCH("RETURNINGOPTION", 15))
		return (Node *) _readReturningOption(ctx);
	if (MATCH("RETURNINGCLAUSE", 15))
		return (Node *) _readReturningClause(ctx);
	if (MATCH("TRIGGERTRANSITION", 17))
		return (Node *) _readTriggerTransition(ctx);
	if (MATCH("JSONOUTPUT", 10))
		return (Node *) _readJsonOutput(ctx);
	if (MATCH("JSONARGUMENT", 12))
		return (Node *) _readJsonArgument(ctx);
	if (MATCH("JSONFUNCEXPR", 12))
		return (Node *) _readJsonFuncExpr(ctx);
	if (MATCH("JSONTABLEPATHSPEC", 17))
		return (Node *) _readJsonTablePathSpec(ctx);
	if (MATCH("JSONTABLEPLANSPEC", 17))
		return (Node *) _readJsonTablePlanSpec(ctx);
	if (MATCH("JSONTABLE", 9))
		return (Node *) _readJsonTable(ctx);
	if (MATCH("JSONTABLECOLUMN", 15))
		return (Node *) _readJsonTableColumn(ctx);
	if (MATCH("JSONKEYVALUE", 12))
		return (Node *) _readJsonKeyValue(ctx);
	if (MATCH("JSONPARSEEXPR", 13))
		return (Node *) _readJsonParseExpr(ctx);
	if (MATCH("JSONSCALAREXPR", 14))
		return (Node *) _readJsonScalarExpr(ctx);
	if (MATCH("JSONSERIALIZEEXPR", 17))
		return (Node *) _readJsonSerializeExpr(ctx);
	if (MATCH("JSONOBJECTCONSTRUCTOR", 21))
		return (Node *) _readJsonObjectConstructor(ctx);
	if (MATCH("JSONARRAYCONSTRUCTOR", 20))
		return (Node *) _readJsonArrayConstructor(ctx);
	if (MATCH("JSONARRAYQUERYCONSTRUCTOR", 25))
		return (Node *) _readJsonArrayQueryConstructor(ctx);
	if (MATCH("JSONAGGCONSTRUCTOR", 18))
		return (Node *) _readJsonAggConstructor(ctx);
	if (MATCH("JSONOBJECTAGG", 13))
		return (Node *) _readJsonObjectAgg(ctx);
	if (MATCH("JSONARRAYAGG", 12))
		return (Node *) _readJsonArrayAgg(ctx);
	if (MATCH("RAWSTMT", 7))
		return (Node *) _readRawStmt(ctx);
	if (MATCH("INSERTSTMT", 10))
		return (Node *) _readInsertStmt(ctx);
	if (MATCH("DELETESTMT", 10))
		return (Node *) _readDeleteStmt(ctx);
	if (MATCH("UPDATESTMT", 10))
		return (Node *) _readUpdateStmt(ctx);
	if (MATCH("MERGESTMT", 9))
		return (Node *) _readMergeStmt(ctx);
	if (MATCH("SELECTSTMT", 10))
		return (Node *) _readSelectStmt(ctx);
	if (MATCH("SETOPERATIONSTMT", 16))
		return (Node *) _readSetOperationStmt(ctx);
	if (MATCH("RETURNSTMT", 10))
		return (Node *) _readReturnStmt(ctx);
	if (MATCH("PLASSIGNSTMT", 12))
		return (Node *) _readPLAssignStmt(ctx);
	if (MATCH("CREATESCHEMASTMT", 16))
		return (Node *) _readCreateSchemaStmt(ctx);
	if (MATCH("ALTERTABLESTMT", 14))
		return (Node *) _readAlterTableStmt(ctx);
	if (MATCH("ALTERTABLECMD", 13))
		return (Node *) _readAlterTableCmd(ctx);
	if (MATCH("ATALTERCONSTRAINT", 17))
		return (Node *) _readATAlterConstraint(ctx);
	if (MATCH("REPLICAIDENTITYSTMT", 19))
		return (Node *) _readReplicaIdentityStmt(ctx);
	if (MATCH("ALTERCOLLATIONSTMT", 18))
		return (Node *) _readAlterCollationStmt(ctx);
	if (MATCH("ALTERDOMAINSTMT", 15))
		return (Node *) _readAlterDomainStmt(ctx);
	if (MATCH("GRANTSTMT", 9))
		return (Node *) _readGrantStmt(ctx);
	if (MATCH("OBJECTWITHARGS", 14))
		return (Node *) _readObjectWithArgs(ctx);
	if (MATCH("ACCESSPRIV", 10))
		return (Node *) _readAccessPriv(ctx);
	if (MATCH("GRANTROLESTMT", 13))
		return (Node *) _readGrantRoleStmt(ctx);
	if (MATCH("ALTERDEFAULTPRIVILEGESSTMT", 26))
		return (Node *) _readAlterDefaultPrivilegesStmt(ctx);
	if (MATCH("COPYSTMT", 8))
		return (Node *) _readCopyStmt(ctx);
	if (MATCH("VARIABLESETSTMT", 15))
		return (Node *) _readVariableSetStmt(ctx);
	if (MATCH("VARIABLESHOWSTMT", 16))
		return (Node *) _readVariableShowStmt(ctx);
	if (MATCH("CREATESTMT", 10))
		return (Node *) _readCreateStmt(ctx);
	if (MATCH("CONSTRAINT", 10))
		return (Node *) _readConstraint(ctx);
	if (MATCH("CREATETABLESPACESTMT", 20))
		return (Node *) _readCreateTableSpaceStmt(ctx);
	if (MATCH("DROPTABLESPACESTMT", 18))
		return (Node *) _readDropTableSpaceStmt(ctx);
	if (MATCH("ALTERTABLESPACEOPTIONSSTMT", 26))
		return (Node *) _readAlterTableSpaceOptionsStmt(ctx);
	if (MATCH("ALTERTABLEMOVEALLSTMT", 21))
		return (Node *) _readAlterTableMoveAllStmt(ctx);
	if (MATCH("CREATEEXTENSIONSTMT", 19))
		return (Node *) _readCreateExtensionStmt(ctx);
	if (MATCH("ALTEREXTENSIONSTMT", 18))
		return (Node *) _readAlterExtensionStmt(ctx);
	if (MATCH("ALTEREXTENSIONCONTENTSSTMT", 26))
		return (Node *) _readAlterExtensionContentsStmt(ctx);
	if (MATCH("CREATEFDWSTMT", 13))
		return (Node *) _readCreateFdwStmt(ctx);
	if (MATCH("ALTERFDWSTMT", 12))
		return (Node *) _readAlterFdwStmt(ctx);
	if (MATCH("CREATEFOREIGNSERVERSTMT", 23))
		return (Node *) _readCreateForeignServerStmt(ctx);
	if (MATCH("ALTERFOREIGNSERVERSTMT", 22))
		return (Node *) _readAlterForeignServerStmt(ctx);
	if (MATCH("CREATEFOREIGNTABLESTMT", 22))
		return (Node *) _readCreateForeignTableStmt(ctx);
	if (MATCH("CREATEUSERMAPPINGSTMT", 21))
		return (Node *) _readCreateUserMappingStmt(ctx);
	if (MATCH("ALTERUSERMAPPINGSTMT", 20))
		return (Node *) _readAlterUserMappingStmt(ctx);
	if (MATCH("DROPUSERMAPPINGSTMT", 19))
		return (Node *) _readDropUserMappingStmt(ctx);
	if (MATCH("IMPORTFOREIGNSCHEMASTMT", 23))
		return (Node *) _readImportForeignSchemaStmt(ctx);
	if (MATCH("CREATEPOLICYSTMT", 16))
		return (Node *) _readCreatePolicyStmt(ctx);
	if (MATCH("ALTERPOLICYSTMT", 15))
		return (Node *) _readAlterPolicyStmt(ctx);
	if (MATCH("CREATEAMSTMT", 12))
		return (Node *) _readCreateAmStmt(ctx);
	if (MATCH("CREATETRIGSTMT", 14))
		return (Node *) _readCreateTrigStmt(ctx);
	if (MATCH("CREATEEVENTTRIGSTMT", 19))
		return (Node *) _readCreateEventTrigStmt(ctx);
	if (MATCH("ALTEREVENTTRIGSTMT", 18))
		return (Node *) _readAlterEventTrigStmt(ctx);
	if (MATCH("CREATEPLANGSTMT", 15))
		return (Node *) _readCreatePLangStmt(ctx);
	if (MATCH("CREATEROLESTMT", 14))
		return (Node *) _readCreateRoleStmt(ctx);
	if (MATCH("ALTERROLESTMT", 13))
		return (Node *) _readAlterRoleStmt(ctx);
	if (MATCH("ALTERROLESETSTMT", 16))
		return (Node *) _readAlterRoleSetStmt(ctx);
	if (MATCH("DROPROLESTMT", 12))
		return (Node *) _readDropRoleStmt(ctx);
	if (MATCH("CREATESEQSTMT", 13))
		return (Node *) _readCreateSeqStmt(ctx);
	if (MATCH("ALTERSEQSTMT", 12))
		return (Node *) _readAlterSeqStmt(ctx);
	if (MATCH("DEFINESTMT", 10))
		return (Node *) _readDefineStmt(ctx);
	if (MATCH("CREATEDOMAINSTMT", 16))
		return (Node *) _readCreateDomainStmt(ctx);
	if (MATCH("CREATEOPCLASSSTMT", 17))
		return (Node *) _readCreateOpClassStmt(ctx);
	if (MATCH("CREATEOPCLASSITEM", 17))
		return (Node *) _readCreateOpClassItem(ctx);
	if (MATCH("CREATEOPFAMILYSTMT", 18))
		return (Node *) _readCreateOpFamilyStmt(ctx);
	if (MATCH("ALTEROPFAMILYSTMT", 17))
		return (Node *) _readAlterOpFamilyStmt(ctx);
	if (MATCH("DROPSTMT", 8))
		return (Node *) _readDropStmt(ctx);
	if (MATCH("TRUNCATESTMT", 12))
		return (Node *) _readTruncateStmt(ctx);
	if (MATCH("COMMENTSTMT", 11))
		return (Node *) _readCommentStmt(ctx);
	if (MATCH("SECLABELSTMT", 12))
		return (Node *) _readSecLabelStmt(ctx);
	if (MATCH("DECLARECURSORSTMT", 17))
		return (Node *) _readDeclareCursorStmt(ctx);
	if (MATCH("CLOSEPORTALSTMT", 15))
		return (Node *) _readClosePortalStmt(ctx);
	if (MATCH("FETCHSTMT", 9))
		return (Node *) _readFetchStmt(ctx);
	if (MATCH("INDEXSTMT", 9))
		return (Node *) _readIndexStmt(ctx);
	if (MATCH("CREATESTATSSTMT", 15))
		return (Node *) _readCreateStatsStmt(ctx);
	if (MATCH("STATSELEM", 9))
		return (Node *) _readStatsElem(ctx);
	if (MATCH("ALTERSTATSSTMT", 14))
		return (Node *) _readAlterStatsStmt(ctx);
	if (MATCH("CREATEFUNCTIONSTMT", 18))
		return (Node *) _readCreateFunctionStmt(ctx);
	if (MATCH("FUNCTIONPARAMETER", 17))
		return (Node *) _readFunctionParameter(ctx);
	if (MATCH("ALTERFUNCTIONSTMT", 17))
		return (Node *) _readAlterFunctionStmt(ctx);
	if (MATCH("DOSTMT", 6))
		return (Node *) _readDoStmt(ctx);
	if (MATCH("CALLSTMT", 8))
		return (Node *) _readCallStmt(ctx);
	if (MATCH("RENAMESTMT", 10))
		return (Node *) _readRenameStmt(ctx);
	if (MATCH("ALTEROBJECTDEPENDSSTMT", 22))
		return (Node *) _readAlterObjectDependsStmt(ctx);
	if (MATCH("ALTEROBJECTSCHEMASTMT", 21))
		return (Node *) _readAlterObjectSchemaStmt(ctx);
	if (MATCH("ALTEROWNERSTMT", 14))
		return (Node *) _readAlterOwnerStmt(ctx);
	if (MATCH("ALTEROPERATORSTMT", 17))
		return (Node *) _readAlterOperatorStmt(ctx);
	if (MATCH("ALTERTYPESTMT", 13))
		return (Node *) _readAlterTypeStmt(ctx);
	if (MATCH("RULESTMT", 8))
		return (Node *) _readRuleStmt(ctx);
	if (MATCH("NOTIFYSTMT", 10))
		return (Node *) _readNotifyStmt(ctx);
	if (MATCH("LISTENSTMT", 10))
		return (Node *) _readListenStmt(ctx);
	if (MATCH("UNLISTENSTMT", 12))
		return (Node *) _readUnlistenStmt(ctx);
	if (MATCH("TRANSACTIONSTMT", 15))
		return (Node *) _readTransactionStmt(ctx);
	if (MATCH("COMPOSITETYPESTMT", 17))
		return (Node *) _readCompositeTypeStmt(ctx);
	if (MATCH("CREATEENUMSTMT", 14))
		return (Node *) _readCreateEnumStmt(ctx);
	if (MATCH("CREATERANGESTMT", 15))
		return (Node *) _readCreateRangeStmt(ctx);
	if (MATCH("ALTERENUMSTMT", 13))
		return (Node *) _readAlterEnumStmt(ctx);
	if (MATCH("VIEWSTMT", 8))
		return (Node *) _readViewStmt(ctx);
	if (MATCH("LOADSTMT", 8))
		return (Node *) _readLoadStmt(ctx);
	if (MATCH("CREATEDBSTMT", 12))
		return (Node *) _readCreatedbStmt(ctx);
	if (MATCH("ALTERDATABASESTMT", 17))
		return (Node *) _readAlterDatabaseStmt(ctx);
	if (MATCH("ALTERDATABASEREFRESHCOLLSTMT", 28))
		return (Node *) _readAlterDatabaseRefreshCollStmt(ctx);
	if (MATCH("ALTERDATABASESETSTMT", 20))
		return (Node *) _readAlterDatabaseSetStmt(ctx);
	if (MATCH("DROPDBSTMT", 10))
		return (Node *) _readDropdbStmt(ctx);
	if (MATCH("ALTERSYSTEMSTMT", 15))
		return (Node *) _readAlterSystemStmt(ctx);
	if (MATCH("VACUUMSTMT", 10))
		return (Node *) _readVacuumStmt(ctx);
	if (MATCH("VACUUMRELATION", 14))
		return (Node *) _readVacuumRelation(ctx);
	if (MATCH("REPACKSTMT", 10))
		return (Node *) _readRepackStmt(ctx);
	if (MATCH("EXPLAINSTMT", 11))
		return (Node *) _readExplainStmt(ctx);
	if (MATCH("CREATETABLEASSTMT", 17))
		return (Node *) _readCreateTableAsStmt(ctx);
	if (MATCH("REFRESHMATVIEWSTMT", 18))
		return (Node *) _readRefreshMatViewStmt(ctx);
	if (MATCH("CHECKPOINTSTMT", 14))
		return (Node *) _readCheckPointStmt(ctx);
	if (MATCH("DISCARDSTMT", 11))
		return (Node *) _readDiscardStmt(ctx);
	if (MATCH("LOCKSTMT", 8))
		return (Node *) _readLockStmt(ctx);
	if (MATCH("CONSTRAINTSSETSTMT", 18))
		return (Node *) _readConstraintsSetStmt(ctx);
	if (MATCH("REINDEXSTMT", 11))
		return (Node *) _readReindexStmt(ctx);
	if (MATCH("CREATECONVERSIONSTMT", 20))
		return (Node *) _readCreateConversionStmt(ctx);
	if (MATCH("CREATECASTSTMT", 14))
		return (Node *) _readCreateCastStmt(ctx);
	if (MATCH("CREATETRANSFORMSTMT", 19))
		return (Node *) _readCreateTransformStmt(ctx);
	if (MATCH("PREPARESTMT", 11))
		return (Node *) _readPrepareStmt(ctx);
	if (MATCH("EXECUTESTMT", 11))
		return (Node *) _readExecuteStmt(ctx);
	if (MATCH("DEALLOCATESTMT", 14))
		return (Node *) _readDeallocateStmt(ctx);
	if (MATCH("DROPOWNEDSTMT", 13))
		return (Node *) _readDropOwnedStmt(ctx);
	if (MATCH("REASSIGNOWNEDSTMT", 17))
		return (Node *) _readReassignOwnedStmt(ctx);
	if (MATCH("ALTERTSDICTIONARYSTMT", 21))
		return (Node *) _readAlterTSDictionaryStmt(ctx);
	if (MATCH("ALTERTSCONFIGURATIONSTMT", 24))
		return (Node *) _readAlterTSConfigurationStmt(ctx);
	if (MATCH("PUBLICATIONTABLE", 16))
		return (Node *) _readPublicationTable(ctx);
	if (MATCH("PUBLICATIONOBJSPEC", 18))
		return (Node *) _readPublicationObjSpec(ctx);
	if (MATCH("PUBLICATIONALLOBJSPEC", 21))
		return (Node *) _readPublicationAllObjSpec(ctx);
	if (MATCH("CREATEPUBLICATIONSTMT", 21))
		return (Node *) _readCreatePublicationStmt(ctx);
	if (MATCH("ALTERPUBLICATIONSTMT", 20))
		return (Node *) _readAlterPublicationStmt(ctx);
	if (MATCH("CREATESUBSCRIPTIONSTMT", 22))
		return (Node *) _readCreateSubscriptionStmt(ctx);
	if (MATCH("ALTERSUBSCRIPTIONSTMT", 21))
		return (Node *) _readAlterSubscriptionStmt(ctx);
	if (MATCH("DROPSUBSCRIPTIONSTMT", 20))
		return (Node *) _readDropSubscriptionStmt(ctx);
	if (MATCH("WAITSTMT", 8))
		return (Node *) _readWaitStmt(ctx);
	if (MATCH("GROUPBYORDERING", 15))
		return (Node *) _readGroupByOrdering(ctx);
	if (MATCH("PLACEHOLDERVAR", 14))
		return (Node *) _readPlaceHolderVar(ctx);
	if (MATCH("APPENDRELINFO", 13))
		return (Node *) _readAppendRelInfo(ctx);
	if (MATCH("PLANNEDSTMT", 11))
		return (Node *) _readPlannedStmt(ctx);
	if (MATCH("RESULT", 6))
		return (Node *) _readResult(ctx);
	if (MATCH("PROJECTSET", 10))
		return (Node *) _readProjectSet(ctx);
	if (MATCH("MODIFYTABLE", 11))
		return (Node *) _readModifyTable(ctx);
	if (MATCH("APPEND", 6))
		return (Node *) _readAppend(ctx);
	if (MATCH("MERGEAPPEND", 11))
		return (Node *) _readMergeAppend(ctx);
	if (MATCH("RECURSIVEUNION", 14))
		return (Node *) _readRecursiveUnion(ctx);
	if (MATCH("BITMAPAND", 9))
		return (Node *) _readBitmapAnd(ctx);
	if (MATCH("BITMAPOR", 8))
		return (Node *) _readBitmapOr(ctx);
	if (MATCH("SEQSCAN", 7))
		return (Node *) _readSeqScan(ctx);
	if (MATCH("SAMPLESCAN", 10))
		return (Node *) _readSampleScan(ctx);
	if (MATCH("INDEXSCAN", 9))
		return (Node *) _readIndexScan(ctx);
	if (MATCH("INDEXONLYSCAN", 13))
		return (Node *) _readIndexOnlyScan(ctx);
	if (MATCH("BITMAPINDEXSCAN", 15))
		return (Node *) _readBitmapIndexScan(ctx);
	if (MATCH("BITMAPHEAPSCAN", 14))
		return (Node *) _readBitmapHeapScan(ctx);
	if (MATCH("TIDSCAN", 7))
		return (Node *) _readTidScan(ctx);
	if (MATCH("TIDRANGESCAN", 12))
		return (Node *) _readTidRangeScan(ctx);
	if (MATCH("SUBQUERYSCAN", 12))
		return (Node *) _readSubqueryScan(ctx);
	if (MATCH("FUNCTIONSCAN", 12))
		return (Node *) _readFunctionScan(ctx);
	if (MATCH("VALUESSCAN", 10))
		return (Node *) _readValuesScan(ctx);
	if (MATCH("TABLEFUNCSCAN", 13))
		return (Node *) _readTableFuncScan(ctx);
	if (MATCH("CTESCAN", 7))
		return (Node *) _readCteScan(ctx);
	if (MATCH("NAMEDTUPLESTORESCAN", 19))
		return (Node *) _readNamedTuplestoreScan(ctx);
	if (MATCH("WORKTABLESCAN", 13))
		return (Node *) _readWorkTableScan(ctx);
	if (MATCH("FOREIGNSCAN", 11))
		return (Node *) _readForeignScan(ctx);
	if (MATCH("CUSTOMSCAN", 10))
		return (Node *) _readCustomScan(ctx);
	if (MATCH("NESTLOOP", 8))
		return (Node *) _readNestLoop(ctx);
	if (MATCH("NESTLOOPPARAM", 13))
		return (Node *) _readNestLoopParam(ctx);
	if (MATCH("MERGEJOIN", 9))
		return (Node *) _readMergeJoin(ctx);
	if (MATCH("HASHJOIN", 8))
		return (Node *) _readHashJoin(ctx);
	if (MATCH("MATERIAL", 8))
		return (Node *) _readMaterial(ctx);
	if (MATCH("MEMOIZE", 7))
		return (Node *) _readMemoize(ctx);
	if (MATCH("SORT", 4))
		return (Node *) _readSort(ctx);
	if (MATCH("INCREMENTALSORT", 15))
		return (Node *) _readIncrementalSort(ctx);
	if (MATCH("GROUP", 5))
		return (Node *) _readGroup(ctx);
	if (MATCH("AGG", 3))
		return (Node *) _readAgg(ctx);
	if (MATCH("WINDOWAGG", 9))
		return (Node *) _readWindowAgg(ctx);
	if (MATCH("UNIQUE", 6))
		return (Node *) _readUnique(ctx);
	if (MATCH("GATHER", 6))
		return (Node *) _readGather(ctx);
	if (MATCH("GATHERMERGE", 11))
		return (Node *) _readGatherMerge(ctx);
	if (MATCH("HASH", 4))
		return (Node *) _readHash(ctx);
	if (MATCH("SETOP", 5))
		return (Node *) _readSetOp(ctx);
	if (MATCH("LOCKROWS", 8))
		return (Node *) _readLockRows(ctx);
	if (MATCH("LIMIT", 5))
		return (Node *) _readLimit(ctx);
	if (MATCH("PLANROWMARK", 11))
		return (Node *) _readPlanRowMark(ctx);
	if (MATCH("PARTITIONPRUNEINFO", 18))
		return (Node *) _readPartitionPruneInfo(ctx);
	if (MATCH("PARTITIONEDRELPRUNEINFO", 23))
		return (Node *) _readPartitionedRelPruneInfo(ctx);
	if (MATCH("PARTITIONPRUNESTEPOP", 20))
		return (Node *) _readPartitionPruneStepOp(ctx);
	if (MATCH("PARTITIONPRUNESTEPCOMBINE", 25))
		return (Node *) _readPartitionPruneStepCombine(ctx);
	if (MATCH("PLANINVALITEM", 13))
		return (Node *) _readPlanInvalItem(ctx);
	if (MATCH("SUBPLANRTINFO", 13))
		return (Node *) _readSubPlanRTInfo(ctx);
	if (MATCH("ELIDEDNODE", 10))
		return (Node *) _readElidedNode(ctx);
	if (MATCH("EXTENSIBLENODE", 14))
		return (Node *) _readExtensibleNode(ctx);
